[profile.default]
src = "src"
out = "out"
libs = ["lib"]

via_ir = true
fuzz_runs = 500
deny_warnings = false

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[rpc_endpoints]
sepolia = "${ETH_SEPOLIA_RPC_URL}"
optimism-sepolia = "${OP_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
optimism-sepolia = { key = "${OPSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
